[package]
name = "test-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jfs = "0.9.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.106" }
